set identity_insert [Skill] on

insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (1 , 'Dual Strike+', 'Adds 10% to the Dual Strike rate', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (2 , 'Charm', 'Hit rate and Avoid +5 to all allies within a 3 tile radius', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (3 , 'Aether', 'Attack twice consecutively, with the first strike having a Sol effect and the second strike having a Luna effect', 'skl', 0.5)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (4 , 'Rightful King', 'Adds 10% to Skill activation rates', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (5 , 'Veteran', 'Experience gain x 1.5 when paired up', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (6 , 'Solidarity', 'Critical and Critical Avoid +10 to adjacent allies', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (7 , 'Ignis', 'Adds (Magic)/2 to Strength when dealing physical damage and (Strength)/2 to Magic when dealing magical damage', 'skl', 1)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (8 , 'Rally Spectrum', 'All stats +4 to all allies within a 3 tile radius for one Turn when the Rally command is used', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (9 , 'Discipline', 'Weapon experience x2', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (10, 'Outdoor Fighter', 'Hit rate and Avoid +10 when fighting outdoors', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (11, 'Defender', 'All stats +1 when paired up', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (12, 'Aegis', 'Halves damage from bows, tomes and dragonstones', 'skl', 1)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (13, 'Luna', 'Ignores half the enemy''s Defense or Resistance', 'skl', 1)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (14, 'Dual Guard+', 'Adds 10% to the Dual Guard rate', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (15, 'Defense +2', 'Defense +2', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (16, 'Indoor Fighter', 'Hit rate and Avoid +10 when fighting indoors', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (17, 'Rally Defense', 'Defense +4 to all allies within a 3 tile radius for one Turn when the Rally command is used', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (18, 'Pavise', 'Halves damage from swords, lances, axes (includes magical variants) and beaststones', 'skl', NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (19, 'Avoid +10', 'Avoid +10', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (20, 'Vantage', 'When HP under half, always attack first during the enemy''s Turn', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (21, 'Astra', 'Deals 5 consecutive hits with half damage', 'skl', 0.5)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (22, 'Swordfaire', 'Strength +5 when equipped with a sword (Magic +5 when equipped with the Levin Sword)', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (23, 'Armsthrift', 'Attack does not reduce weapon usage', 'lck', 2)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (24, 'Patience', 'Hit rate and Avoid +10 during the enemy’s Turn', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (25, 'Sol', 'Recover HP equal to half the damage dealt to the enemy', 'skl', 1)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (26, 'Axebreaker', 'Hit rate and Avoid +50 when the enemy is equipped with an axe', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (27, 'HP +5', 'Maximum HP +5', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (28, 'Zeal', 'Critical +5', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (29, 'Rally Strength', 'Strength +4 to all allies within a 3 tile radius for one Turn when the Rally command is used', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (30, 'Counter', 'Returns damage when attacked by an adjacent enemy (except damage that KOs the user)', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (31, 'Despoil', 'Obtain Bullion (S) from the enemy if the user defeats the enemy', 'lck', 1)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (32, 'Gamble', 'Hit rate -5, Critical +10', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (33, 'Wrath', 'Critical +20 when under half HP', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (34, 'Axefaire', 'Strength +5 when equipped with an axe (Magic +5 when equipped with the Bolt Axe)', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (35, 'Skill +2', 'Skill +2', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (36, 'Prescience', 'Hit rate and Avoid +15 during the user''s Turn', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (37, 'Hit Rate +20', 'Hit rate +20', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (38, 'Bowfaire', 'Strength +5 when equipped with a bow', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (39, 'Rally Skill', 'Skill +4 to all allies within a 3 tile radius for one Turn when the Rally command is used', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (40, 'Bowbreaker', 'Hit rate and Avoid +50 when the enemy is equipped with a bow', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (41, 'Locktouch', 'Open doors and chests without the need of keys', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (42, 'Movement +1', 'Movement +1', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (43, 'Lethality', 'Instantly defeats the enemy', 'skl', 0.25)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (44, 'Pass', 'User can pass through tiles occupied by enemy units', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (45, 'Lucky Seven', 'Hit rate and Avoid +20 up to the 7th Turn', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (46, 'Acrobat', 'All traversable terrain costs 1 movement point to cross', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (47, 'Speed +2', 'Speed +2', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (48, 'Relief', 'Recover 20% HP at the start of the user''s Turn if no units are within a 3 tile radius', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (49, 'Rally Speed', 'Speed +4 to all allies within a 3 tile radius for one Turn when the Rally command is used', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (50, 'Lancefaire', 'Strength +5 when equipped with a lance (Magic +5 when equipped with the Shockstick)', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (51, 'Rally Movement', 'Movement +1 to all allies within a 3 tile radius for one Turn when the Rally command is used', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (52, 'Galeforce', 'Allows the user another full action after they defeat an enemy during the user''s Turn (only once per Turn)', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (53, 'Strength +2', 'Strength +2', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (54, 'Tantivy', 'Strength +2', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (55, 'Quick Burn', 'Hit rate and Avoid +15 at the start of the chapter. Effect decreases with each passing Turn', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (56, 'Swordbreaker', 'Hit rate and Avoid +50 when the enemy is equipped with a sword', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (57, 'Deliverer', 'Movement +2 when paired up', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (58, 'Lancebreaker', 'Hit rate and Avoid +50 when the enemy is equipped with a lance', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (59, 'Magic +2', 'Magic +2', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (60, 'Focus', 'Critical +10 when no allies within a 3 tile radius', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (61, 'Rally Magic', 'Magic +4 to all allies within a 3 tile radius for one Turn when the Rally command is used', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (62, 'Tomefaire', 'Magic +5 when equipped with a Tome', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (63, 'Hex', 'Avoid -15 to all adjacent enemies', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (64, 'Anathema', 'Avoid and Critical Avoid -10 to all enemies within a 3 tile radius', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (65, 'Vengeance', 'Deals (user’s Max HP – Current HP)/2 extra damage', 'skl', 2)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (66, 'Tomebreaker', 'Hit rate and Avoid +50 when the enemy is equipped with a tome', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (67, 'Slow Burn', 'Hit rate and Avoid increases by 1 each Turn, up to the 15th Turn', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (68, 'Lifetaker', 'User recovers 50% HP after they defeat an enemy during the user''s Turn', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (69, 'Miracle', 'Character survives with 1 HP after receiving an attack that would otherwise KO them (must have over 1 HP)', 'lck', 1)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (70, 'Healtouch', 'Restores an extra 5 HP when healing allies', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (71, 'Rally Luck', 'Luck +8 to all allies within a 3 tile radius for one Turn when the Rally command is used', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (72, 'Renewal', 'Recover 30% HP at the start of the user’s Turn', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (73, 'Resistance +2', 'Resistance +2', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (74, 'Demoiselle', 'Avoid and Critical Avoid +10 to all male allies within a 3 tile radius', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (75, 'Rally Resistance', 'Resistance +4 to all allies within a 3 tile radius for one Turn when the Rally command is used', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (76, 'Dual Support+', 'Increases the support bonus effect', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (77, 'Aptitude', 'Adds 20% to all growth rates during Level Ups', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (78, 'Underdog', 'Hit rate and Avoid +15 when user''s Level is lower than the enemy (promoted units count as Level +20)', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (79, 'Luck +4', 'Luck +4', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (80, 'Special Dance', 'Strength, Magic, Defense and Resistance +2 for one Turn for the unit who receives the user''s Dance', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (81, 'Even Rhythm', 'Hit rate and Avoid +10 during even numbered Turns', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (82, 'Beastbane', 'Deals effective damage to Beast units when user is a Taguel', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (83, 'Odd Rhythm', 'Hit rate and Avoid +10 during odd numbered Turns', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (84, 'Wyrmsbane', 'Deals effective damage to Dragon units when user is a Manakete', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (85, 'Shadowgift', 'Enables usage of Dark Tomes for Tome wielders', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (86, 'Conquest', 'Negates user’s Beast and Armor type weaknesses', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (87, 'Resistance +10', 'Resistance +10', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (88, 'Aggressor', 'Attack +10 during the user''s Turn', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (89, 'Rally Heart', 'All stats +2 and Movement +1 to all allies within a 3 tile radius for one Turn when the Rally command is used', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (90, 'Bond', 'Restores 10 HP to all allies within a 3 tile radius at the beginning of the user''s Turn', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (91, 'All Stats +2', 'Strength, Magic, Skill, Speed, Luck, Defense and Resistance +2', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (92, 'Paragon', 'Experience gain x2', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (93, 'Iote''s Shield', 'Negates user''s Flying type weakness', NULL, NULL)    
insert into [Skill] ([Id], [Name], [Description], [ActivationStat], [ActivationMultiplier]) values (94, 'Limit Breaker', 'Raises the character''s maximum stats by 10', NULL, NULL)    

set identity_insert [Skill] off
